spring:
  application:
    name: hotel
  profiles:
    active: dev

server:
  port: 8080

logging:
  level:
    root: info
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel-db?currentSchema=public&TimeZone=America/Sao_Paulo
    username: postgres
    password: postgres
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:tc:postgresql:15.2:///?stringtype=unspecified
    username: user
    password: password
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update